//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App2 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App2.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string AboutUp {
            get {
                return ResourceManager.GetString("AboutUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assists per game:.
        /// </summary>
        internal static string APG {
            get {
                return ResourceManager.GetString("APG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string AtlantaString {
            get {
                return ResourceManager.GetString("AtlantaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Birth date:.
        /// </summary>
        internal static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 17-x NBA Champions.
        /// </summary>
        internal static string BostonString {
            get {
                return ResourceManager.GetString("BostonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x Conference Champions.
        /// </summary>
        internal static string BrooklynString {
            get {
                return ResourceManager.GetString("BrooklynString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string CharlotteString {
            get {
                return ResourceManager.GetString("CharlotteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6-x NBA Champions.
        /// </summary>
        internal static string ChicagoString {
            get {
                return ResourceManager.GetString("ChicagoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string ClevelandString {
            get {
                return ResourceManager.GetString("ClevelandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string DallasString {
            get {
                return ResourceManager.GetString("DallasString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8-x Division Champions.
        /// </summary>
        internal static string DenverString {
            get {
                return ResourceManager.GetString("DenverString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3-x NBA Champions.
        /// </summary>
        internal static string DetroitString {
            get {
                return ResourceManager.GetString("DetroitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eastern conference.
        /// </summary>
        internal static string EasternConference {
            get {
                return ResourceManager.GetString("EasternConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Foundation year:.
        /// </summary>
        internal static string FoundationLabel {
            get {
                return ResourceManager.GetString("FoundationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5-x NBA Champions.
        /// </summary>
        internal static string GSWString {
            get {
                return ResourceManager.GetString("GSWString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Head coach:.
        /// </summary>
        internal static string HeadCoach {
            get {
                return ResourceManager.GetString("HeadCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home arena:.
        /// </summary>
        internal static string HomeArena {
            get {
                return ResourceManager.GetString("HomeArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x NBA Champions.
        /// </summary>
        internal static string HoustonString {
            get {
                return ResourceManager.GetString("HoustonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x Conference Champions.
        /// </summary>
        internal static string IndianaString {
            get {
                return ResourceManager.GetString("IndianaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x Division Champions.
        /// </summary>
        internal static string LAClippersString {
            get {
                return ResourceManager.GetString("LAClippersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 16-x NBA Champions.
        /// </summary>
        internal static string LALakersString {
            get {
                return ResourceManager.GetString("LALakersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  .
        /// </summary>
        internal static string MemphisString {
            get {
                return ResourceManager.GetString("MemphisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3-x NBA Champions.
        /// </summary>
        internal static string MiamiString {
            get {
                return ResourceManager.GetString("MiamiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string MilwaukeeString {
            get {
                return ResourceManager.GetString("MilwaukeeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x Division Champions.
        /// </summary>
        internal static string MinnesotaString {
            get {
                return ResourceManager.GetString("MinnesotaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minutes per game:.
        /// </summary>
        internal static string MPG {
            get {
                return ResourceManager.GetString("MPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nationality:.
        /// </summary>
        internal static string NationalityLabel {
            get {
                return ResourceManager.GetString("NationalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x Division Champions.
        /// </summary>
        internal static string NewOrleansString {
            get {
                return ResourceManager.GetString("NewOrleansString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x NBA Champions.
        /// </summary>
        internal static string NewYorkString {
            get {
                return ResourceManager.GetString("NewYorkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string OklahomaString {
            get {
                return ResourceManager.GetString("OklahomaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x Conference Champions.
        /// </summary>
        internal static string OrlandoString {
            get {
                return ResourceManager.GetString("OrlandoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3-x NBA Champions.
        /// </summary>
        internal static string PhilaString {
            get {
                return ResourceManager.GetString("PhilaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x Conference Champions.
        /// </summary>
        internal static string PhoenixString {
            get {
                return ResourceManager.GetString("PhoenixString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Players.
        /// </summary>
        internal static string PlayersButton {
            get {
                return ResourceManager.GetString("PlayersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        internal static string PlayerTitle {
            get {
                return ResourceManager.GetString("PlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string PortlandString {
            get {
                return ResourceManager.GetString("PortlandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        internal static string PositionSort {
            get {
                return ResourceManager.GetString("PositionSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points per game:.
        /// </summary>
        internal static string PPG {
            get {
                return ResourceManager.GetString("PPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roster.
        /// </summary>
        internal static string RosterButton {
            get {
                return ResourceManager.GetString("RosterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rebounds per game:.
        /// </summary>
        internal static string RPG {
            get {
                return ResourceManager.GetString("RPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string SacramentoString {
            get {
                return ResourceManager.GetString("SacramentoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsUp {
            get {
                return ResourceManager.GetString("SettingsUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by:.
        /// </summary>
        internal static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5-x NBA Champions.
        /// </summary>
        internal static string SpursString {
            get {
                return ResourceManager.GetString("SpursString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stats.
        /// </summary>
        internal static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surname.
        /// </summary>
        internal static string SurnameSort {
            get {
                return ResourceManager.GetString("SurnameSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animation.
        /// </summary>
        internal static string SwitchSet {
            get {
                return ResourceManager.GetString("SwitchSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teams.
        /// </summary>
        internal static string TeamsButton {
            get {
                return ResourceManager.GetString("TeamsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Team.
        /// </summary>
        internal static string TeamSort {
            get {
                return ResourceManager.GetString("TeamSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string TorontoString {
            get {
                return ResourceManager.GetString("TorontoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Training camp:.
        /// </summary>
        internal static string TrainingCamp {
            get {
                return ResourceManager.GetString("TrainingCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-x Conference Champions.
        /// </summary>
        internal static string UtahString {
            get {
                return ResourceManager.GetString("UtahString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1-x NBA Champions.
        /// </summary>
        internal static string WashingtonString {
            get {
                return ResourceManager.GetString("WashingtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Western conference.
        /// </summary>
        internal static string WesternConference {
            get {
                return ResourceManager.GetString("WesternConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch on YouTube.
        /// </summary>
        internal static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
